language: python
python:
- 3.6
- 3.7
sudo: false
before_install:
- if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh
  -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh
  -O miniconda.sh; fi
- chmod +x miniconda.sh
- ./miniconda.sh -b
- export PATH=/home/travis/anaconda/bin:/home/travis/miniconda/bin:/home/travis/miniconda/bin:/home/travis/miniconda3/bin:$PATH
- conda update --yes conda
install:
- conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy nose cython
- pip install nose-cov python-coveralls pyMKL
- conda install --yes -c conda-forge properties discretize
- python setup.py install
script:
- nosetests --with-cov --cov pymatsolver --cov-config .coveragerc -v -s
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack: simpeg:1KZq5giMtlJJ58TijIPgqf7n
