language: python
python:
- 2.7
- 3.4
- 3.5
- 3.6
matrix:
  allow_failures:
    - python: 3.6
sudo: false
before_install:
- if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh
  -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh
  -O miniconda.sh; fi
- chmod +x miniconda.sh
- ./miniconda.sh -b
- export PATH=/home/travis/anaconda/bin:/home/travis/miniconda/bin:/home/travis/miniconda/bin:/home/travis/miniconda3/bin:$PATH
- conda update --yes conda
install:
- conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy nose cython
- pip install nose-cov python-coveralls pyMKL
- git clone https://github.com/simpeg/discretize.git; cd discretize; python setup.py
  install; cd ..;
- python setup.py install
- python setup.py build_ext --inplace
script:
- nosetests --with-cov --cov pymatsolver --cov-config .coveragerc -v -s
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack: simpeg:1KZq5giMtlJJ58TijIPgqf7n
